# compose 파일 버전
version: "3"
services:
  # 서비스 명
  postgresql:
    image: postgres
    restart: always
    container_name: HTDiary
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: ysh8614
      POSTGRES_PASSWORD: 8614